language: python

#List the versions of python to test against
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

branches:
  only:
    - master
jobs:
  include:
    - script: setup.py test

notifications:
  email:
    - develop@bjornlarsson.net
