language: python

#List the versions of python to test against
python:
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  only:
    - master

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

script: python setup.py test

notifications:
  email:
    - develop@bjornlarsson.net
